#!/usr/bin/env node
// Regenerate src/spec/asc-spec.ts from Apple's App Store Connect OpenAPI file.
//
//   curl -sSLO https://developer.apple.com/sample-code/app-store-connect/app-store-connect-openapi-specification.zip
//   unzip app-store-connect-openapi-specification.zip
//   node scripts/gen-spec.mjs openapi.oas.json
//
// The output lets feature tools offer only the actions Apple's API really has,
// and fill in relationship types without hand-written tables.
import { readFileSync, writeFileSync } from 'node:fs';

const specPath = process.argv[2];
if (!specPath) {
  console.error('usage: node scripts/gen-spec.mjs <openapi.oas.json>');
  process.exit(1);
}
const spec = JSON.parse(readFileSync(specPath, 'utf8'));
const schemas = spec.components.schemas;

const refName = (ref) => ref.split('/').pop();

function writeShape(schemaName) {
  const data = schemas[schemaName]?.properties?.data;
  const type = data?.properties?.type?.enum?.[0];
  // Link-only bodies (data is an array of ids) are not resource writes.
  if (!type) return undefined;
  const attrsSchema = data.properties?.attributes ?? {};
  const relsSchema = data.properties?.relationships ?? {};
  const rels = {};
  for (const [name, rel] of Object.entries(relsSchema.properties ?? {})) {
    const relData = rel.properties?.data;
    if (!relData) continue;
    const many = relData.type === 'array';
    const type = (many ? relData.items : relData)?.properties?.type?.enum?.[0];
    if (!type) continue;
    rels[name] = { type, many, required: (relsSchema.required ?? []).includes(name) };
  }
  return {
    type,
    attributes: Object.keys(attrsSchema.properties ?? {}),
    requiredAttributes: attrsSchema.required ?? [],
    relationships: rels,
  };
}

const paths = {};
const writes = {};
for (const [path, ops] of Object.entries(spec.paths).sort(([a], [b]) => a.localeCompare(b))) {
  const methods = Object.keys(ops).filter((m) => m !== 'parameters').map((m) => m.toUpperCase()).sort();
  paths[path] = methods;
  for (const method of ['POST', 'PATCH']) {
    const ref = ops[method.toLowerCase()]?.requestBody?.content?.['application/json']?.schema?.$ref;
    if (!ref) continue;
    const shape = writeShape(refName(ref));
    if (shape) writes[`${method} ${path}`] = shape;
  }
}

const out = `// GENERATED by scripts/gen-spec.mjs from Apple's App Store Connect OpenAPI spec. Do not edit by hand.
export const SPEC_VERSION = ${JSON.stringify(spec.info.version)};

export type WriteShape = {
  type: string;
  attributes: string[];
  requiredAttributes: string[];
  relationships: Record<string, { type: string; many: boolean; required: boolean }>;
};

export const PATHS: Record<string, string[]> = ${JSON.stringify(paths)};

export const WRITES: Record<string, WriteShape> = ${JSON.stringify(writes)};
`;
writeFileSync(new URL('../src/spec/asc-spec.ts', import.meta.url), out);
console.log(`spec ${spec.info.version}: ${Object.keys(paths).length} paths, ${Object.keys(writes).length} write shapes`);
